services:
  tika-metadata-tool:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - /home/User/data:/data
      - /home/User/logs:/logs
      - /home/User/output:/output
      - /home/User/excel:/excel
    environment:
      - TIKA_SERVER_JAR=/app/tika.jar